### PR TITLE
Update runtime to 44

### PR DESCRIPTION
**Pull request by bbhtt**
Ping @Emersont1 for review. Thanks! :)

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by hfiguiere** [comment]
Issue #3 talks about the music folder...

**Comment by bbhtt** [comment]
> Issue #3 talks about the music folder...

Ah right didn't see that one. Indeed the Music directory is the default location:

image

I'll change it to that.

It also seems to run in wayland without x11 and fallback-x11, so I'll add that as well. It uses GTK3...

**Comment by hfiguiere** [comment]
Also https://github.com/flathub/flathub/pull/2051#pullrequestreview-569613924 and https://github.com/flathub/flathub/pull/2051#issuecomment-762148423

I'd rather have this updated to build from source instead to have an aarch64 build.

**Comment by bbhtt** [comment]
> I'd rather have this updated to build from source instead to have an aarch64 build.

Is there is a way to specify the PMM packages in a separate manifest and have them build offline? I can't find it https://github.com/vector-of-bool/pmm#i-dont-want-to-automatically-download-and-run-code-from-the-internet, https://github.com/Microsoft/vcpkg/issues/4795#issuecomment-491169371 Also I think it'd require patches to make it stop connecting to the PMM server during build and use locally downloaded packages (if it's possible) because it still does https://github.com/Emersont1/big-finish-downloader/blob/c6c754e65a827a500dad3c9d847fd723ce3e2fb4/pmm.cmake#L37 and thus a source build fails with:

```
CMake Error at pmm.cmake:71 (message):
  Failed to download PMM entry file: "Couldn't resolve host name"
Call Stack (most recent call first):
  CMakeLists.txt:15 (include)
```

**Comment by hfiguiere** [comment]
yeah it's poorly designed.

**Comment by bbhtt** [comment]
I'll drop the filesystem access change (pending on comments from Emersont1), so that at least the runtime bump can be merged.

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> Build [113722 successful](https://buildbot.flathub.org/#/builders/32/builds/113722) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/111329/uk.et1.big-finish-downloader.flatpakref
> ```

Runs

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
cc @hfiguiere can we merge this too? It's also on a horribly out of date runtime and @Emersont1 hasn't been active for over a year. 

Thanks!

**Pull request merged**
